
spring:
  datasource:
  url: jdbc:mysql://127.0.0.1:3306/testeeleicoes?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  useranme: develop
  password: develop


flyway:
  user: develop
  password: develop

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG